In [13]:
import numpy as np
import scipy

In [14]:
V=np.array([[0.63,0.03,0.86,0.29,0.60,0.99],[0.45,0.40,0.17,0.79,0.38,0.43],[0.87,0.86,0.16,0.04,0.15,0.76]])
W=np.array([[0.17,0.26,0.78,0.83,0.69,0.64],[0.03,0.37,0.65,0.96,0.72,0.77],[0.50,0.15,0.67,0.82,0.04,0.34]])

In [19]:
#TRIAD
error=[]
for i in range(6):
    for j in range(6):
        if i!=j:
            v1=V[:,i]
            v2=V[:,j]
            w1=W[:,i]
            w2=W[:,j]
            r1=v1/(np.sqrt(np.sum(v1**2)))
            r2=np.cross(v1,v2)
            r2=r2/(np.sqrt(np.sum(r2**2)))
            r3=np.cross(r1,r2)
            s1=w1/(np.sqrt(np.sum(w1**2)))
            s2=np.cross(w1,w2)
            s2=s2/(np.sqrt(np.sum(s2**2)))
            s3=np.cross(s1,s2)
            Mobs=np.array([s1,s2,s3]).T
            Mref=np.array([r1,r2,r3]).T
            A=np.matmul(Mobs,Mref.T)
            if(i==0 and j==1):
                print(A)
            e=W-np.matmul(A,V)
            sqe=np.sum(e*e)
            error.append(sqe)
            print('Sum of squared errors for vectors (',i+1,',',j+1,') = ',sqe)
min_error=np.min(error)
print(min_error)


[[-0.25513326  0.95960231  0.11861881]
 [-0.66794375 -0.26361786  0.69595744]
 [ 0.69911241  0.0983312   0.70821805]]
Sum of squared errors for vectors ( 1 , 2 ) =  8.761209982551708
Sum of squared errors for vectors ( 1 , 3 ) =  3.982949162194488
Sum of squared errors for vectors ( 1 , 4 ) =  3.669461697326299
Sum of squared errors for vectors ( 1 , 5 ) =  3.2208490895156356
Sum of squared errors for vectors ( 1 , 6 ) =  4.378053694780402
Sum of squared errors for vectors ( 2 , 1 ) =  5.387011205009763
Sum of squared errors for vectors ( 2 , 3 ) =  5.377002708270709
Sum of squared errors for vectors ( 2 , 4 ) =  6.362287258446778
Sum of squared errors for vectors ( 2 , 5 ) =  7.06092300335579
Sum of squared errors for vectors ( 2 , 6 ) =  5.985628740354525
Sum of squared errors for vectors ( 3 , 1 ) =  4.1654084183687585
Sum of squared errors for vectors ( 3 , 2 ) =  3.7721338619623745
Sum of squared errors for vectors ( 3 , 4 ) =  3.699475435720793
Sum of squared errors for vectors (

In [16]:
#QUEST
#Normalized
V1=V
W1=W
for j in range(6):
    V1[:,j]/=np.sqrt(np.sum(V[:,j]**2))
    W1[:,j]/=np.sqrt(np.sum(V[:,j]**2))
a=np.ones(6)
a=a/np.sum(a)
B=np.zeros([3,3])
Z=np.zeros(3)
for i in range(6):
    vi=np.array([V1[:,i]]).T
    wi=np.array([W1[:,i]]).T
    B+=a[i]*np.matmul(wi,vi.T)
    vi=V1[:,i]
    wi=W1[:,i]
    Z+=a[i]*np.cross(wi,vi)
sigma=np.trace(B)
S=B+B.T
TL=S-sigma*np.eye(3)
K=np.zeros([4,4])
K[0:3,0:3]=TL
K[0:3,3]=Z
K[3,0:3]=Z
K[3,3]=sigma
l,q0=np.linalg.eig(K)
qopt=q0[:,np.argmax(l)]
q=qopt[3]
Q=qopt[0:3]
Q_t=np.array([[0,Q[2],-Q[1]],[-Q[2],0,Q[0]],[Q[1],-Q[0],0]])
Q=np.array([Q]).T
A=(q**2-np.sum(Q**2))*np.eye(3)+2*np.matmul(Q,Q.T)+2*q*Q_t
print(A)
e=W-np.matmul(A,V)
sqe=np.sum(e*e)
print('Sum of squared errors=',sqe)

[[ 0.97824434 -0.19170497  0.07929199]
 [ 0.20364119  0.96030898 -0.19062246]
 [-0.03960153  0.20262246  0.97845585]]
Sum of squared errors= 2.5152519641610804


In [17]:
#Wahba
V1=V
W1=W
for j in range(6):
    V1[:,j]/=np.sqrt(np.sum(V[:,j]**2))
    W1[:,j]/=np.sqrt(np.sum(V[:,j]**2))
A=np.matmul(W1,V1.T)
U,P=scipy.linalg.polar(A)
D,N=scipy.linalg.eig(P)
D=np.diag(D)
k=len(D)
X=np.eye(k)
if (np.linalg.det(U)>-1.01 and np.linalg.det(U)<-0.99):
    X[k-1,k-1]=-1
M=np.matmul(U,np.matmul(N.T,np.matmul(X.T,N)))
print(np.linalg.det(M))
print(M)
E=W1-np.matmul(M,V1)
sqe=np.matmul(E.T,E)
print('Sum of squared errors=',np.trace(sqe))

1.0
[[ 0.97824434 -0.19170497  0.07929199]
 [ 0.20364119  0.96030898 -0.19062246]
 [-0.03960153  0.20262246  0.97845585]]
Sum of squared errors= 2.5152519641610804
