In [1]:
import numpy as np
import scipy

In [95]:
W1=np.array([[0.17,0.26,0.78,0.83,0.69,0.64],[0.03,0.37,0.65,0.96,0.72,0.77],[0.50,0.15,0.67,0.82,0.04,0.34]])
V1=np.array([[0.63,0.03,0.86,0.29,0.60,0.99],[0.45,0.40,0.17,0.79,0.38,0.43],[0.87,0.86,0.16,0.04,0.15,0.76]])
for i in range(len(W[0])):
    W[:,i]=W1[:,i]/np.sqrt(np.matmul(W1[:,i].T,W1[:,i]))
    V[:,i]=V1[:,i]/np.sqrt(np.matmul(V1[:,i].T,V1[:,i]))
#print(W)
#print(W1)

In [96]:
A=np.matmul(W1,V1.T)
U,P=scipy.linalg.polar(A)
D,N=scipy.linalg.eig(P)
D=np.diag(D)
k=len(D)
X=np.eye(k)
if (np.linalg.det(U)>-1.01 and np.linalg.det(U)<-0.99):
    X[k-1,k-1]=-1
M=np.matmul(U,np.matmul(N.T,np.matmul(X.T,N)))
print(np.linalg.det(M))
print(M)

1.000000000000001
[[ 0.97307269 -0.21660168  0.07882421]
 [ 0.22659041  0.96160772 -0.15481402]
 [-0.042265    0.16850611  0.98479407]]


In [97]:
E=W1-np.matmul(M,V1)
E0=W1-V1
sqe=np.matmul(E.T,E)
sqe0=np.matmul(E0.T,E0)
print('Sum of squared errors=',np.trace(sqe))
print('RMSE=',np.sqrt(np.trace(sqe)/6))

Sum of squared errors= 2.951774052773257
RMSE= 0.7014002724043356
